version: '3.8'

services:
  db:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: cyfrowauczelnia
      MYSQL_USER: studentadmin
      MYSQL_PASSWORD: mypassword
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
    ports:
      - "3306:3306" 

  www:
    build: 
      context: . 
      dockerfile: Dockerfile 
    volumes:
      - "./:/var/www/html" 
    ports:
      - "80:80" 
      - "443:443" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306 
    depends_on:
      - db 
